= Learn to Design and Verify a 6-stage pipelined RISC-V CPU
(c) Rishiyur S. Nikhil, Bluespec, Inc. 2025
:revnumber: v0.800
:revdate: 2025-08-15
:imagesdir: Doc/Figs
:keywords: Bluespec, B-Lang, BSV, BH, RISC-V, Pipelined CPU, HDL, HLHDL, High Level Hardware Design Language, Fife, Drum

// ****************************************************************

[NOTE]
====
This document's source is `README.adoc` and can be read as-is in a
text-editor or terminal.  It can also be processed with the free,
open-source `asciidoctor` tool into `README.html` and viewed in any
browser.  GitHub will automatically process and display .adoc
documents.
====

// ****************************************************************

This repository holds materials for the following tutorial:

[.excerpt]
____
"Learn to Design and Verify a 6-stage pipelined RISC-V CPU" +
at the RISC-V Summit, Santa Clara, CA, "Developer's Day", October 22, 2025 +
Instructor: Rishiyur S. Nikhil, Ph.D., CTO and Co-founder, Bluespec, Inc.
____

This repository contains:

* link:Doc/Tutorial_Description.txt[A brief description of the
  tutorial] (same as on
  link:https://riscv.org/community/risc-v-summits/[RISCV.org^]
  website)
+
Please visit the
  link:https://riscv.org/community/risc-v-summits/[RISCV.org^] website
  if you wish to register for and attend the summit or the tutorial.

* link:Slides_Placeholder.pdf[PDF slides] for the tutorial
  (placeholder for now; will be made available shortly before the
  tutorial date).

* Instructions for acquiring and installing all resources/tools
  (link:Doc/Resources.adoc[adoc],link:Doc/Resources.html[html]) needed
  for "hands-on" participation (all are free and open-source).
+
[IMPORTANT]
====

*We strongly recommend that you download and install resources in
 advance of the tutorial at the RISC-V Summit.*

Due to the limited time available at the tutorial, we cannot afford to
spend any time at the tutorial on resource downloading and
installation.

====

This tutorial includes major live, "hands-on" components:

* Reading excerpts of actual source code of the CPU hardware design
* Building simulation executables for the CPU and running it on RISC-V code
* Verifying the CPU by running it in a verification environment

Although this tutorial can fruitfully be attended just as an ordinary
lecture (i.e., observe slides and demos on the big screen), *you will
get much more value* if you participate in the "hands-on" segments
(during and after the tutorial), by code-reading, simulating and
verifying on your own laptop.
